version: 2
updates:
- package-ecosystem: nuget
  directory: "/PreMailer.Net/PreMailer.Net.Tests"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/PreMailer.Net/PreMailer.Net"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
